only build on version tag

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -1,6 +1,8 @@
 name: Release cli on github
 on:
   push:
+    tags:
+      - "v*"
 
 jobs:
   build-cli-binaries:
@@ -29,8 +31,7 @@ jobs:
         shell: bash
     steps:
       - uses: actions/checkout@v4
-        with:
-          ref: v0.1.2
+
       - name: install protoc
         uses: arduino/setup-protoc@v3
         with:
@@ -54,8 +55,21 @@ jobs:
 
       - name: build the CLI
         run: |
-          export RELEASE_VERSION="0.1.2"
-          echo "RELEASE_VERSION = ${RELEASE_VERSION}"
+          # If we're on a tag, use the tag name as the release version.
+          if [[ "$GITHUB_REF_TYPE" == 'tag' ]]; then
+            # Ensure that the version specified in Cargo.toml is the same as the tag (with a 'v' prefix).
+            CARGO_VERSION="$(cargo metadata --format-version=1 | jq -r '.packages | .[] | select(.name == "ndc-test") | .version')"
+            echo "Git tag: ${GITHUB_REF_NAME}"
+            echo "Cargo version: ${CARGO_VERSION}"
+
+            if [[ "${GITHUB_REF_NAME}" != "v${CARGO_VERSION}" ]]; then
+              echo >&2 "The Git tag is \"${GITHUB_REF_NAME}\", but the version in Cargo.toml is \"${CARGO_VERSION}\"."
+              echo >&2 'These must be the same, with a "v" prefix for the tag. Aborting.'
+              exit 1
+            fi
+            export RELEASE_VERSION="$GITHUB_REF_NAME"
+            echo "RELEASE_VERSION = ${RELEASE_VERSION}"
+          fi
 
           if [[ -n '${{ matrix.linker }}' ]]; then
             TARGET_SCREAMING="$(echo '${{ matrix.target }}' | tr '[:lower:]' '[:upper:]' | tr '-' '_')"
@@ -81,7 +95,7 @@ jobs:
     needs:
       - build-cli-binaries
     runs-on: ubuntu-latest
-    # if: ${{ startsWith(github.ref, 'refs/tags/v') }}
+    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
     steps:
       - uses: actions/checkout@v4
 
@@ -95,7 +109,7 @@ jobs:
           set -evo pipefail
           ROOT="$(pwd)"
 
-          export CLI_VERSION="v0.1.2"
+          export CLI_VERSION="$GITHUB_REF_NAME"
 
           export LINUX_AMD64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-test-x86_64-unknown-linux-musl     | cut -f1 -d' ')
           export MACOS_AMD64_SHA256=$(sha256sum ${ROOT}/release/artifacts/ndc-test-x86_64-apple-darwin           | cut -f1 -d' ')
@@ -106,7 +120,7 @@ jobs:
       - name: Get version from tag
         id: get-version
         run: |
-          echo "tagged_version=0.1.2" >> $GITHUB_OUTPUT
+          echo "tagged_version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
         shell: bash
 
       - name: create a draft release
